---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root

  tasks:
  - name: ensure libselinux-python is at the latest version
    yum: name=libselinux-python state=latest

  - name: ensure keepalived is at the latest version
    yum: name=keepalived state=latest

  - name: ensure haproxy is at the latest version
    yum: name=haproxy state=latest

  - name: write the haproxy config file
    template: src=src/haproxy.conf.j2 dest=/etc/haproxy/haproxy.conf
    notify:
    - restart haproxy

  - name: ensure keepalived is running (and enable it at boot)
    service: name=keepalived state=started enabled=yes

  - name: ensure haproxy is running (and enable it at boot)
    service: name=haproxy state=started enabled=yes

  handlers:
    - name: restart keepalived
      service: name=keepalived state=restarted

    - name: restart haproxy
      service: name=haproxy state=restarted
